spring:
  application:
    name: gulimall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4Fg7fkxoNL25LU1oKkZP
      secret-key: uMj4ZYlDoAO7ZcgjZqJM4W0pZv2Ck6
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: education-project
      sms:
        host: https://smsmsgs.market.alicloudapi.com
        path: /sms/
        appcode: 619e570411294bc380ba50c68f0d604a


server:
  port: 30000
